name: CI/CD Workflow

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker-compose build  # Zbudowanie obrazu z Docker Compose

    - name: Run the application
      run: |
        docker-compose run app ./build/WSEIDevOps

    - name: Run tests
      run: |
        docker-compose run test ./build/exampleTest
